### ISSUE TITLE
Make `scenario_player` a well-behaved CLI tool

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/scenario-player#193]
Generally speaking, well behaved cli tools fulfill the following requirements:

- [x] Accept CLI flags 
- [x] Work with files
- [ ] Work with STDIN and STDOUT (see `fileinput`)
- [ ] Communicates via its exit status codes
- [ ] handles signals
- [ ] respects resource limits

**Comment by ulope** [comment]
> Work with STDIN and STDOUT (see fileinput)

What part should be passable via stdin? The scenario files? That already works by passing `-` as the filename (although it's not recommended since the scenario name is derived from the filename).

`stdout` is normally used by the UI (which has now been fixed).

> Communicates via its exit status codes

It already does that. If that isn't the case anymore it most likely didn't survive some refactoring.

> handles signals

Same as above, should work (although when the UI is active it will stay up after the scenario has finished running to allow reading the output).

> respects resource limits

Not sure what that would entail.

**Comment by palango** [comment]
Not actionable, we'll create issues when problem appear.
