### ISSUE TITLE
Allow using existing token or minting

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#572]
Currently the SP expects that tokens are mintable so that the required nodes can be founded properly.

During mainnet testing this prerequisite was not fulfilled any more and some adaptions had to be done in order to use existing tokens in the SP account.

We should merge those changes into the SP and make it optional to use existing token instead of minting them.

### Tasks
- [ ] Add an option to use existing tokens to the scenario file
- [ ] Merge https://github.com/karlb/scenario-player/tree/testing/mainnet-no-mint
- [ ] Merge https://github.com/raiden-network/scenario-player/pull/571
