### ISSUE TITLE
Release Service

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#60]
The scenario player downloads raiden binaries as archives from our DO space during set-up.

This is done by checking for the presence of an archive with the same name as pointed to by the `_LATEST-*` file on the DO space is present on disk.

Problem
=======

We currently do not check for validty of files, and do not perform clean up actions. Removing old archives includes ssh-ing into the server and manually removing them.

Downloaded archives and unpacked binaries are not tracked beyond a scenario run.

It's currently not possible to specify a release archive for download.

Solution
======

We propose the creation of a `Release Manager` service with the following domain:

- Downloading archives
- Unpacking archives
- Removing archives
- Installing Binaries
- removing Binaries
- Tracking of files downloaded, unpacked and installed using the service
- Validation of archives using checksums (need to be provided first)
- validating origin / signature of archives/binaries
- Providing install/download paths to the files

-----------------------------------------------------------
To-Dos
======
- [x] Write stubs for blueprints, components (#37)
- [x] Write unit-test harness (#37)
- [ ] Write integration-test harness

**Comment by palango** [comment]
Closing. See https://github.com/raiden-network/scenario-player/issues/495
