### ISSUE TITLE
Measure performance of a scenario

### ISSUE THREAD

**Issue by jondoe1337** [raiden-network/scenario-player#84]
I opened this issue to discuss and summarize the feedback/results of the current state of the analysis tool for the scenario player, currently getting reviewed in: https://github.com/raiden-network/scenario-player/pull/41

As of the latest sync-call (today) with @ulope we agreed on the following things:
- [ ] the hops calculation cannot be done right now as it is based on the node-ids and will have wrong results in most cases (e.g. Pathfinding); Ad hoc solution was to implement a debug endpoint in the client to get more information (e.g. hops) about a given transfer-id; @ulope will create an issue about that
- [x]  the hops column will be removed (@jondoe1337)
- [x]  the descriptive statistics will be extended to have it on each task group (all tasks grouped by type and then applied with stats) and moved to an own file (@jondoe1337)
- [x]  each descriptive statistic will have a histogram to show the distribution of the duration of all task of that type (@jondoe1337)

**Comment by christianbrb** [comment]
Done, but without analyzing multiple hops. It's within this repo: https://github.com/raiden-network/performance-analysis-tool
